apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    name: demo-app
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      name: demo-app
      labels:
        app: demo-app
        name: demo-app
    spec:
      restartPolicy: Always
      containers:
      - name: demo-app
        image: jantampos/demo-app:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            protocol: TCP
        env:
          - name: KEYCLOAK_URL
            value: "http://192.168.64.9:30000/auth"
          - name: SERVICE_URL
            value: "http://192.168.64.9:30080"
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 400m
            memory: 512Mi

---

apiVersion: v1
kind: Service
metadata:
  name: demo-app
  labels:
    app: demo-app
    name: demo-app
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 30070
  selector:
    app: demo-app
    name: demo-app