apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    name: demo-app
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      name: demo-app
      labels:
        app: demo-app
        name: demo-app
    spec:
      restartPolicy: Always
      containers:
      - name: demo-app
        image: gcr.io/k8s--projects/demo-app
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            protocol: TCP
        env:
          - name: KEYCLOAK_URL
            value: "http://35.247.187.36/auth"
          - name: SERVICE_URL
            value: "http://34.87.11.189"
            # value: "http://35.240.176.215"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  labels:
    app: demo-app
    name: demo-app
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: demo-app
    name: demo-app