apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service-php
  labels:
    app: demo-service-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-service-php
  template:
    metadata:
      name: demo-service-php
      labels:
        app: demo-service-php
    spec:
      restartPolicy: Always
      containers:
      - name: demo-service-php-app
        image: gcr.io/k8s--projects/demo-service-php
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            protocol: TCP
        env:
          - name: KEYCLOAK_URL
            value: "http://35.247.187.36/auth"
      - name: service-proxy
        image: keycloak/keycloak-gatekeeper
        imagePullPolicy: Always
        args:
          - --config=/etc/config/keycloak-gatekeeper.yml
        ports:
          - containerPort: 9090
        env:
          - name: KEYCLOAK_URL
            value: "http://35.247.187.36/auth"
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: gatekeeper-config
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service-php
  labels:
    app: demo-service-php
    name: demo-service-php
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9090
  selector:
    app: demo-service-php
