apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service-php
  labels:
    app: demo-service-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-service-php
  template:
    metadata:
      name: demo-service-php
      labels:
        app: demo-service-php
    spec:
      restartPolicy: Always
      containers:
      - name: demo-service-php-app
        image: jantampos/demo-service-php:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            protocol: TCP
        env:
          - name: KEYCLOAK_URL
            value: "http://192.168.64.9:30000/auth"
      - name: proxy
        image: quay.io/gambol99/keycloak-proxy:latest
        imagePullPolicy: Always
        args:
          - --config=/etc/config/keycloak-gatekeeper.yml
        ports:
          - containerPort: 9090
        env:
          - name: KEYCLOAK_URL
            value: "http://192.168.64.9:30000/auth"
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: gatekeeper-config
---

apiVersion: v1
kind: Service
metadata:
  name: demo-service-php
  labels:
    app: demo-service-php
    name: demo-service-php
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 9090
      nodePort: 30090
  selector:
    app: demo-service-php
